version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/demo-db
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    container_name: postgresql-container
    environment:
      - 'POSTGRES_DB=demo-db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: